#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tk
Version  : 8.6.5
Release  : 8
URL      : http://downloads.sourceforge.net/tcl/tk8.6.5-src.tar.gz
Source0  : http://downloads.sourceforge.net/tcl/tk8.6.5-src.tar.gz
Summary  : Tk graphical toolkit for the Tcl scripting language.
Group    : Development/Tools
License  : TCL
Requires: tk-bin
Requires: tk-doc
Requires: tk-data
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : tcl

%description
The Tcl (Tool Command Language) provides a powerful platform for
creating integration applications that tie together diverse
applications, protocols, devices, and frameworks.  When paired with
the Tk toolkit, Tcl provides the fastest and most powerful way to
create GUI applications that run on PCs, Unix, and Mac OS X.  Tcl
can also be used for a variety of web-related tasks and for creating
powerful command languages for applications.

%package bin
Summary: bin components for the tk package.
Group: Binaries
Requires: tk-data

%description bin
bin components for the tk package.


%package data
Summary: data components for the tk package.
Group: Data

%description data
data components for the tk package.


%package dev
Summary: dev components for the tk package.
Group: Development
Requires: tk-bin
Requires: tk-data
Provides: tk-devel

%description dev
dev components for the tk package.


%package doc
Summary: doc components for the tk package.
Group: Documentation

%description doc
doc components for the tk package.


%prep
%setup -q -n tk8.6.5

%build
pushd unix/
%configure --disable-static
make V=1  %{?_smp_mflags}
popd

%install
rm -rf %{buildroot}
pushd unix/
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib/tk8.6/bgerror.tcl
/usr/lib/tk8.6/button.tcl
/usr/lib/tk8.6/choosedir.tcl
/usr/lib/tk8.6/clrpick.tcl
/usr/lib/tk8.6/comdlg.tcl
/usr/lib/tk8.6/console.tcl
/usr/lib/tk8.6/demos/README
/usr/lib/tk8.6/demos/anilabel.tcl
/usr/lib/tk8.6/demos/aniwave.tcl
/usr/lib/tk8.6/demos/arrow.tcl
/usr/lib/tk8.6/demos/bind.tcl
/usr/lib/tk8.6/demos/bitmap.tcl
/usr/lib/tk8.6/demos/browse
/usr/lib/tk8.6/demos/button.tcl
/usr/lib/tk8.6/demos/check.tcl
/usr/lib/tk8.6/demos/clrpick.tcl
/usr/lib/tk8.6/demos/colors.tcl
/usr/lib/tk8.6/demos/combo.tcl
/usr/lib/tk8.6/demos/cscroll.tcl
/usr/lib/tk8.6/demos/ctext.tcl
/usr/lib/tk8.6/demos/dialog1.tcl
/usr/lib/tk8.6/demos/dialog2.tcl
/usr/lib/tk8.6/demos/en.msg
/usr/lib/tk8.6/demos/entry1.tcl
/usr/lib/tk8.6/demos/entry2.tcl
/usr/lib/tk8.6/demos/entry3.tcl
/usr/lib/tk8.6/demos/filebox.tcl
/usr/lib/tk8.6/demos/floor.tcl
/usr/lib/tk8.6/demos/fontchoose.tcl
/usr/lib/tk8.6/demos/form.tcl
/usr/lib/tk8.6/demos/goldberg.tcl
/usr/lib/tk8.6/demos/hello
/usr/lib/tk8.6/demos/hscale.tcl
/usr/lib/tk8.6/demos/icon.tcl
/usr/lib/tk8.6/demos/image1.tcl
/usr/lib/tk8.6/demos/image2.tcl
/usr/lib/tk8.6/demos/images/earth.gif
/usr/lib/tk8.6/demos/images/earthris.gif
/usr/lib/tk8.6/demos/images/face.xbm
/usr/lib/tk8.6/demos/images/flagdown.xbm
/usr/lib/tk8.6/demos/images/flagup.xbm
/usr/lib/tk8.6/demos/images/gray25.xbm
/usr/lib/tk8.6/demos/images/letters.xbm
/usr/lib/tk8.6/demos/images/noletter.xbm
/usr/lib/tk8.6/demos/images/ouster.png
/usr/lib/tk8.6/demos/images/pattern.xbm
/usr/lib/tk8.6/demos/images/tcllogo.gif
/usr/lib/tk8.6/demos/images/teapot.ppm
/usr/lib/tk8.6/demos/items.tcl
/usr/lib/tk8.6/demos/ixset
/usr/lib/tk8.6/demos/knightstour.tcl
/usr/lib/tk8.6/demos/label.tcl
/usr/lib/tk8.6/demos/labelframe.tcl
/usr/lib/tk8.6/demos/license.terms
/usr/lib/tk8.6/demos/mclist.tcl
/usr/lib/tk8.6/demos/menu.tcl
/usr/lib/tk8.6/demos/menubu.tcl
/usr/lib/tk8.6/demos/msgbox.tcl
/usr/lib/tk8.6/demos/nl.msg
/usr/lib/tk8.6/demos/paned1.tcl
/usr/lib/tk8.6/demos/paned2.tcl
/usr/lib/tk8.6/demos/pendulum.tcl
/usr/lib/tk8.6/demos/plot.tcl
/usr/lib/tk8.6/demos/puzzle.tcl
/usr/lib/tk8.6/demos/radio.tcl
/usr/lib/tk8.6/demos/rmt
/usr/lib/tk8.6/demos/rolodex
/usr/lib/tk8.6/demos/ruler.tcl
/usr/lib/tk8.6/demos/sayings.tcl
/usr/lib/tk8.6/demos/search.tcl
/usr/lib/tk8.6/demos/spin.tcl
/usr/lib/tk8.6/demos/states.tcl
/usr/lib/tk8.6/demos/style.tcl
/usr/lib/tk8.6/demos/tclIndex
/usr/lib/tk8.6/demos/tcolor
/usr/lib/tk8.6/demos/text.tcl
/usr/lib/tk8.6/demos/textpeer.tcl
/usr/lib/tk8.6/demos/timer
/usr/lib/tk8.6/demos/toolbar.tcl
/usr/lib/tk8.6/demos/tree.tcl
/usr/lib/tk8.6/demos/ttkbut.tcl
/usr/lib/tk8.6/demos/ttkmenu.tcl
/usr/lib/tk8.6/demos/ttknote.tcl
/usr/lib/tk8.6/demos/ttkpane.tcl
/usr/lib/tk8.6/demos/ttkprogress.tcl
/usr/lib/tk8.6/demos/ttkscale.tcl
/usr/lib/tk8.6/demos/twind.tcl
/usr/lib/tk8.6/demos/unicodeout.tcl
/usr/lib/tk8.6/demos/vscale.tcl
/usr/lib/tk8.6/demos/widget
/usr/lib/tk8.6/dialog.tcl
/usr/lib/tk8.6/entry.tcl
/usr/lib/tk8.6/focus.tcl
/usr/lib/tk8.6/fontchooser.tcl
/usr/lib/tk8.6/iconlist.tcl
/usr/lib/tk8.6/icons.tcl
/usr/lib/tk8.6/images/README
/usr/lib/tk8.6/images/logo.eps
/usr/lib/tk8.6/images/logo100.gif
/usr/lib/tk8.6/images/logo64.gif
/usr/lib/tk8.6/images/logoLarge.gif
/usr/lib/tk8.6/images/logoMed.gif
/usr/lib/tk8.6/images/pwrdLogo.eps
/usr/lib/tk8.6/images/pwrdLogo100.gif
/usr/lib/tk8.6/images/pwrdLogo150.gif
/usr/lib/tk8.6/images/pwrdLogo175.gif
/usr/lib/tk8.6/images/pwrdLogo200.gif
/usr/lib/tk8.6/images/pwrdLogo75.gif
/usr/lib/tk8.6/images/tai-ku.gif
/usr/lib/tk8.6/listbox.tcl
/usr/lib/tk8.6/megawidget.tcl
/usr/lib/tk8.6/menu.tcl
/usr/lib/tk8.6/mkpsenc.tcl
/usr/lib/tk8.6/msgbox.tcl
/usr/lib/tk8.6/msgs/cs.msg
/usr/lib/tk8.6/msgs/da.msg
/usr/lib/tk8.6/msgs/de.msg
/usr/lib/tk8.6/msgs/el.msg
/usr/lib/tk8.6/msgs/en.msg
/usr/lib/tk8.6/msgs/en_gb.msg
/usr/lib/tk8.6/msgs/eo.msg
/usr/lib/tk8.6/msgs/es.msg
/usr/lib/tk8.6/msgs/fr.msg
/usr/lib/tk8.6/msgs/hu.msg
/usr/lib/tk8.6/msgs/it.msg
/usr/lib/tk8.6/msgs/nl.msg
/usr/lib/tk8.6/msgs/pl.msg
/usr/lib/tk8.6/msgs/pt.msg
/usr/lib/tk8.6/msgs/ru.msg
/usr/lib/tk8.6/msgs/sv.msg
/usr/lib/tk8.6/obsolete.tcl
/usr/lib/tk8.6/optMenu.tcl
/usr/lib/tk8.6/palette.tcl
/usr/lib/tk8.6/panedwindow.tcl
/usr/lib/tk8.6/safetk.tcl
/usr/lib/tk8.6/scale.tcl
/usr/lib/tk8.6/scrlbar.tcl
/usr/lib/tk8.6/spinbox.tcl
/usr/lib/tk8.6/tclIndex
/usr/lib/tk8.6/tearoff.tcl
/usr/lib/tk8.6/text.tcl
/usr/lib/tk8.6/tk.tcl
/usr/lib/tk8.6/tkAppInit.c
/usr/lib/tk8.6/tkfbox.tcl
/usr/lib/tk8.6/ttk/altTheme.tcl
/usr/lib/tk8.6/ttk/aquaTheme.tcl
/usr/lib/tk8.6/ttk/button.tcl
/usr/lib/tk8.6/ttk/clamTheme.tcl
/usr/lib/tk8.6/ttk/classicTheme.tcl
/usr/lib/tk8.6/ttk/combobox.tcl
/usr/lib/tk8.6/ttk/cursors.tcl
/usr/lib/tk8.6/ttk/defaults.tcl
/usr/lib/tk8.6/ttk/entry.tcl
/usr/lib/tk8.6/ttk/fonts.tcl
/usr/lib/tk8.6/ttk/menubutton.tcl
/usr/lib/tk8.6/ttk/notebook.tcl
/usr/lib/tk8.6/ttk/panedwindow.tcl
/usr/lib/tk8.6/ttk/progress.tcl
/usr/lib/tk8.6/ttk/scale.tcl
/usr/lib/tk8.6/ttk/scrollbar.tcl
/usr/lib/tk8.6/ttk/sizegrip.tcl
/usr/lib/tk8.6/ttk/spinbox.tcl
/usr/lib/tk8.6/ttk/treeview.tcl
/usr/lib/tk8.6/ttk/ttk.tcl
/usr/lib/tk8.6/ttk/utils.tcl
/usr/lib/tk8.6/ttk/vistaTheme.tcl
/usr/lib/tk8.6/ttk/winTheme.tcl
/usr/lib/tk8.6/ttk/xpTheme.tcl
/usr/lib/tk8.6/unsupported.tcl
/usr/lib/tk8.6/xmfbox.tcl
/usr/lib64/tk8.6/pkgIndex.tcl
/usr/lib64/tkConfig.sh

%files bin
%defattr(-,root,root,-)
/usr/bin/wish8.6

%files data
%defattr(-,root,root,-)
/usr/share/man/mann/bell.n
/usr/share/man/mann/bind.n
/usr/share/man/mann/bindtags.n
/usr/share/man/mann/bitmap.n
/usr/share/man/mann/busy.n
/usr/share/man/mann/button.n
/usr/share/man/mann/canvas.n
/usr/share/man/mann/checkbutton.n
/usr/share/man/mann/clipboard.n
/usr/share/man/mann/colors.n
/usr/share/man/mann/console.n
/usr/share/man/mann/cursors.n
/usr/share/man/mann/destroy.n
/usr/share/man/mann/entry.n
/usr/share/man/mann/event.n
/usr/share/man/mann/focus.n
/usr/share/man/mann/font.n
/usr/share/man/mann/fontchooser.n
/usr/share/man/mann/frame.n
/usr/share/man/mann/geometry.n
/usr/share/man/mann/grab.n
/usr/share/man/mann/grid.n
/usr/share/man/mann/image.n
/usr/share/man/mann/keysyms.n
/usr/share/man/mann/label.n
/usr/share/man/mann/labelframe.n
/usr/share/man/mann/listbox.n
/usr/share/man/mann/lower.n
/usr/share/man/mann/menu.n
/usr/share/man/mann/menubutton.n
/usr/share/man/mann/message.n
/usr/share/man/mann/option.n
/usr/share/man/mann/options.n
/usr/share/man/mann/pack.n
/usr/share/man/mann/pack_old.n
/usr/share/man/mann/panedwindow.n
/usr/share/man/mann/photo.n
/usr/share/man/mann/place.n
/usr/share/man/mann/radiobutton.n
/usr/share/man/mann/raise.n
/usr/share/man/mann/safe_loadTk.n
/usr/share/man/mann/scale.n
/usr/share/man/mann/scrollbar.n
/usr/share/man/mann/selection.n
/usr/share/man/mann/send.n
/usr/share/man/mann/spinbox.n
/usr/share/man/mann/text.n
/usr/share/man/mann/tk.n
/usr/share/man/mann/tk_bindForTraversal.n
/usr/share/man/mann/tk_bisque.n
/usr/share/man/mann/tk_chooseColor.n
/usr/share/man/mann/tk_chooseDirectory.n
/usr/share/man/mann/tk_dialog.n
/usr/share/man/mann/tk_focusFollowsMouse.n
/usr/share/man/mann/tk_focusNext.n
/usr/share/man/mann/tk_focusPrev.n
/usr/share/man/mann/tk_getOpenFile.n
/usr/share/man/mann/tk_getSaveFile.n
/usr/share/man/mann/tk_library.n
/usr/share/man/mann/tk_mac.n
/usr/share/man/mann/tk_menuBar.n
/usr/share/man/mann/tk_menuSetFocus.n
/usr/share/man/mann/tk_messageBox.n
/usr/share/man/mann/tk_optionMenu.n
/usr/share/man/mann/tk_patchLevel.n
/usr/share/man/mann/tk_popup.n
/usr/share/man/mann/tk_setPalette.n
/usr/share/man/mann/tk_strictMotif.n
/usr/share/man/mann/tk_textCopy.n
/usr/share/man/mann/tk_textCut.n
/usr/share/man/mann/tk_textPaste.n
/usr/share/man/mann/tk_version.n
/usr/share/man/mann/tkerror.n
/usr/share/man/mann/tkwait.n
/usr/share/man/mann/toplevel.n
/usr/share/man/mann/ttk_button.n
/usr/share/man/mann/ttk_checkbutton.n
/usr/share/man/mann/ttk_combobox.n
/usr/share/man/mann/ttk_entry.n
/usr/share/man/mann/ttk_frame.n
/usr/share/man/mann/ttk_image.n
/usr/share/man/mann/ttk_intro.n
/usr/share/man/mann/ttk_label.n
/usr/share/man/mann/ttk_labelframe.n
/usr/share/man/mann/ttk_menubutton.n
/usr/share/man/mann/ttk_notebook.n
/usr/share/man/mann/ttk_panedwindow.n
/usr/share/man/mann/ttk_progressbar.n
/usr/share/man/mann/ttk_radiobutton.n
/usr/share/man/mann/ttk_scale.n
/usr/share/man/mann/ttk_scrollbar.n
/usr/share/man/mann/ttk_separator.n
/usr/share/man/mann/ttk_sizegrip.n
/usr/share/man/mann/ttk_spinbox.n
/usr/share/man/mann/ttk_style.n
/usr/share/man/mann/ttk_treeview.n
/usr/share/man/mann/ttk_vsapi.n
/usr/share/man/mann/ttk_widget.n
/usr/share/man/mann/winfo.n
/usr/share/man/mann/wm.n

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
